export const GAMBLING_QUOTES = [
  "99% of gamblers quit before their biggest win.",
  "The house always wins. Unless it doesn't. Today feels special.",
  "Quitters never win. Financially responsible people never feel this alive.",
  "Your future self is begging you to double down.",
  "What are the odds? Don't answer that.",
  "Every billionaire was once called irresponsible.",
  "It's not gambling. It's aggressively believing in yourself.",
  "The Titanic was built by professionals. The Ark was built by a guy with faith.",
  "Scared money don't make money.",
  "You miss 100% of the bets you don't place. — Wayne Gretzky — Michael Scott",
  "A wise man once said: 'run it back.'",
  "The casino needs your money way less than you need theirs.",
  "Debt is temporary. Glory is forever.",
  "Remember: the slot machine is legally required to pay eventually. Probably.",
  "If bad decisions didn't work sometimes, nobody would make them.",
  "This next spin has insane lore potential.",
  "Imagine quitting right before the script flips.",
  "You're not losing money. You're paying for character development.",
  "Fortune favors the financially questionable.",
  "The grind never stops. Neither should you.",
  "Your bank account is holding you back from greatness.",
  "The odds fear confident people.",
  "One more spin and history changes forever.",
  "Hakuna Matata. It means all-in.",
  "The wolf of Wall Street would not cash out here.",
  "In the casino of life, today is your anime comeback arc.",
  "Caesar didn't cross the Rubicon to play it safe.",
  "The roulette wheel can smell fear.",
  "You didn't come this far to stop being irresponsible now.",
  "It's only a gambling addiction if you're losing.",
  "Some people stop before they win. You're built different.",
  "This is either a terrible idea or an incredible story.",
  "The math is fake. The feeling is real.",
  "Your lucky streak is just socially anxious.",
  "Every spin gets you closer to statistically impossible wealth.",
  "Keep going. The casino employees are starting to believe in you.",
  "Never back down never what?",
  "What if the real jackpot was the delusions we made along the way.",
  "Financial stability is temporary. Legends are eternal.",
  "The slot machine called you cute.",
  "One more hand. The universe literally hinted at it.",
  "Your ancestors didn't survive plagues for you to cash out early.",
  "A gambler and his money are soon partying.",
  "This machine hasn't paid out in hours. It's basically charged up.",
  "You're not chasing losses. You're following the plot.",
  "If this was a bad idea, why would it feel so cinematic?",
  "Double or nothing builds character.",
  "Reality is temporary. The spin is forever.",
  "Go big or explain to your friends why you left early.",
  "You can't spell jackpot without 'cope.'",
  "Trust the process. Ignore the statistics.",
  "The casino hates to see a visionary coming.",
  "If at first you don't succeed, increase the bet size.",
  "Some call it reckless. Others call it destiny.",
  "The numbers are random, but your aura isn't.",
  "The next hand is sponsored by destiny.",
  "You're either about to be rich or gain a life lesson.",
  "The slot machine whispered your name.",
  "All gamblers stop right before the machine gets emotional.",
  "Today's forecast: 2% chance of rain, 98% chance of generational wealth.",
] as const

export function pickQuote(exclude?: number): number {
  const len = GAMBLING_QUOTES.length
  let idx = Math.floor(Math.random() * len)
  if (exclude !== undefined && len > 1 && idx === exclude) {
    idx = (idx + 1) % len
  }
  return idx
}
